# Generated by Django 5.0.6 on 2024-05-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="psuedonym",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
